### ISSUE TITLE
Is the model updated for the new season?

### ISSUE THREAD

**Issue by tejrai13** [nealmick/bb#24]
I was looking at the 76ers vs. Bucks game (10/26/23, 7:30 PM) and I noticed the team lineups haven't been updated with the off-season trades and roster changes (ex. Dame is on the Blazers and not the Bucks according to the model). 

Will there be any updates soon?

Thank you

**Comment by nealmick** [comment]
Yea the player rosters dont update automatically, you can search for players or click on a player name to go to there detail page.  From there you can click update team or update stats, it will call the api for updated stats.....
I do have a script that will loop over recent games and update all the players, but that only works after a few games into the season.... The bigger problem is the api is reporting old stale data... happens every season start... the folks over at balldontlie.io should be updating hopefully soon, then the system will start to pickup the correct data....

**Comment by tejrai13** [comment]
Went and tried to update Dame, still shows Blazers. Probably as you said, people at balldontlie.io have to update there info.

**Comment by nealmick** [comment]
Okay API is updated and seems to be reporting correct stats.  I found my old update roster script too.  Should be done in a bit ill push tomorrow.  however new player discovery will need to wait until we have observed playtime in at least 1 game from any new players.

**Comment by nealmick** [comment]
Okay rosters is updated, still waiting for spread api to list tomorrows odds.  Once the odds are detected we should be in a relatively good state for the new season.

**Comment by nealmick** [comment]
odds api is up and reporting today's games.  Let me know if you see any messed up data.

**Comment by tejrai13** [comment]
Not sure if rosters are updated fully, I still see Dame on the Blazers for today's game.

**Comment by nealmick** [comment]
I mean your not wrong, i see the game on your account here:
https://nbadata.cloud/predict/edit/7458/

but when i try to reproduce it, like i just created this one, it has correct roster:
https://nbadata.cloud/predict/edit/7460/

It says there wasn't any players removed, could you try again to see if it continues??
The main roster seems correct here:
https://nbadata.cloud/predict/team/POR

and the player profile looks good here:
https://nbadata.cloud/predict/player-details/278

and its not like that game was created a while ago it looks like just now....

it says its models slot 0, i mean maybe a custom model causing it but i doubt it?? 

could you try again and see if its still messed up??? do the other links show correctly on the player page or team page???  also maybe try with base model and like default settings.... reset one of your model slots and don't modify the data when creating the game, test if that works maybe??? im still not able to reproduce, even if i login to the demo account it seems to be correct as-well.  I mean if all else fails maybe give the demo account a try.....
