### ISSUE TITLE
How do these statistics work? 

### ISSUE THREAD

**Issue by Sausalitos** [nealmick/bb#25]
Hello! I would like to know how it works? It is a script that gives prediction of game winner or. Only from players? Thank you and sorry for the doubt

![Screenshot_2023-10-24-18-40-51-120_com android chrome](https://github.com/nealmick/bb/assets/131852471/6b6c3191-8e8d-451d-8318-6c61ca86e481)

**Comment by nealmick** [comment]
Yes its not just player stats, models can be trained with a wide range of input features.  Some of the data points we offer are the players season averages. The default model inputs the top 7 players by play time for each team.  In addition to the top 7 players we also input the top 5 players stats for each teams last game (with opponents, and scores).  We also input team level stats such as season win/loss record, as well as win/loss streaks. We also offer vegas odds data, particular point spread which can be set as a model input.  Models can be trained with any combination of these data points, i would just like to stress the website is mainly developed for computers, not mobile phones... But yes overall the goal of the project is to collect correlated data features and use them to model game outcomes. 

![68747470733a2f2f692e696d6775722e636f6d2f676437415256692e706e67](https://github.com/nealmick/bb/assets/33704976/c7b62d72-ee82-4842-9146-2f4eb1245c06)

![68747470733a2f2f692e696d6775722e636f6d2f784a4d6d765a522e706e67](https://github.com/nealmick/bb/assets/33704976/c63875a1-f13f-492a-b574-6adfc783bfcb)
