### ISSUE TITLE
update stats all players

### ISSUE THREAD

**Issue by Ivanfut7** [nealmick/bb#36]
there are something to update stats of all players? or I must go 1 to 1

**Comment by nealmick** [comment]
I mean that would take a long time haha... idea is update as needed.... notice a player gets traded then update team.... season averages are very long time frame, don't change much.  I did have a script for this but couldn't find it just now.

To be honest im starting to wind down this project,  I dont see massive improvements incoming, just btw, welcome to use this for whatever its useful for... but new major features are most likely not coming, unless something change... 

I caution anyone from getting involved with 0 sum games like this.  Very easy to get attached, and not want to move on to something better after 4 years, the next feature always fixes it, the answer is always to just keep working at it.  Its a dangerous idea, I mean i definitely benefited massively from everything i learned building this, but jeeeeeesh man.  Now i want to work on something more positive, i will make decentralized crowd funded city clean up app or something physically useful and solve a real world problem.   The bar for this stuff, way higher then i could have ever imagined.  You want to predict the future, I wish you speed and strength, may god be with you.

**Comment by nealmick** [comment]
btw did find the script that updates all stats forgot what i named it:
https://github.com/nealmick/bb/blob/main/util/test.py

that should loop over all the players in the local cache and update all the season averages.... please dont run this often. its season averages, currently it looks like its set to 1.5 second delay for each request.  If you really do decide to run this i recommend upping the time sleep to 3 second per player or whatever.  Then run it overnight, and it will update all the players slowly... If you request more then 60 times in a second server shuts down... also this may error if you run in from within the util folder, may have to move the file back to the root of the project so it cant find the pkl object files.....
